### ISSUE TITLE
Realm CLI installation failed: Error: Only Windows 64 bits supported.

### ISSUE THREAD

**Issue by Khoosham** [10gen/realm-cli#201]
I am trying to install realm-cli via npm globally using the following command `npm install -g mongodb-realm-cli`

Windows 10 64 Bit
![image](https://user-images.githubusercontent.com/16463632/131888824-8d20e9d3-2135-49e1-ab0c-4c757261b79b.png)

But this results in the following error.

```
npm install -g mongodb-realm-cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
C:\Users\XX\AppData\Roaming\npm\realm-cli -> C:\Users\XX\AppData\Roaming\npm\node_modules\mongodb-realm-cli\wrapper.js

> mongodb-realm-cli@2.1.0 install C:\Users\XX\AppData\Roaming\npm\node_modules\mongodb-realm-cli
> node install.js

Realm CLI installation failed: Error: Only Windows 64 bits supported.
    at getdownloadURL (C:\Users\XX\AppData\Roaming\npm\node_modules\mongodb-realm-cli\install.js:32:13)
    at Object.<anonymous> (C:\Users\XX\AppData\Roaming\npm\node_modules\mongodb-realm-cli\install.js:95:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mongodb-realm-cli@2.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mongodb-realm-cli@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XX\AppData\Roaming\npm-cache\_logs\2021-09-02T16_39_32_533Z-debug.log
```

**Comment by Khoosham** [comment]
As a workaround for now, I was able to compile the code to produce the exe
